name: Test workflow
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: do-something
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Job 1 Step 1
        id: step0
        run: | 
          echo Doing Something...
          touch test.1
          touch test.2
          touch test.3
      - name: Job 1 Step 2
        id: step1
        run: |
          MY_STRING=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          echo "test=$MY_STRING" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2 Step 1
        run: echo Doing Something...
      - name: Job 2 Step 2
        run: echo ${{needs.job1.outputs.output1}}
